name: Docker Image push

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the codebase
      uses: actions/checkout@v3
    
    - name: Login into the docker hub
      
      env: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      run: |
          docker login -u $username -p $password
    - name: Build docker image
       # run: docker build . --file Dockerfile --tag rsundararajandocker/php-app:${{ github.sha }}
      run: docker build . --file Dockerfile --tag rsundararajandocker/docker-session:v2

    - name: Docker push
      run: docker push rsundararajandocker/docker-session:v2  
