# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
          
      # Example 1
      - name: Check for new commits today
        id: check-new-commits
        uses: adriangl/check-new-commits-action@v1

      # NOTE: `since_last_remote_commit: true` is implied by default and falls back to the previous local commit.

      - name: Print something if new commits are found
        if: ${{ steps.check-new-commits.outputs.has-new-commits == 'true' }}
        run: echo "You have ${{ steps.check-new-commits.outputs.new-commits-number }} new commit(s) !"
        
      - name: Print another thing if new commits couldn't be found
        if: ${{ steps.check-new-commits.outputs.has-new-commits != 'true' }}
        run: echo "You don't have new commits !"
